//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandOver
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransferWorkEntities : DbContext
    {
        public TransferWorkEntities()
            : base("name=TransferWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<EVM> EVMs { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Model> Models1 { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
