//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandOver
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string CardID { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string VnName { get; set; }
        public string EnName { get; set; }
        public string CnName { get; set; }
        public string Avata { get; set; }
        public int Role { get; set; }
        public string Department { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
