//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandOver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int ID { get; set; }
        public System.DateTime DateStart { get; set; }
        public string Type { get; set; }
        public string WorkDes { get; set; }
        public string OwnerRequest { get; set; }
        public string OwnerReceive { get; set; }
        public string Status { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> DateClose { get; set; }
        public string HistoryLog { get; set; }
        public string Flow { get; set; }
        public string CTF { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    }
}
